.PHONY: help build test run run-cmis run-mia fmt fmt-check lint check audit deny coverage clean \
        formal formal-tamarin formal-cryptoverif docs docker-image docker-image-push \
        docker-repo-setup docker-repo-show mia-install mia-uninstall \
        pkg pkg-deb pkg-rpm pkg-msi pkg-macos pkg-tools pkg-sdk release deploy-release

# Default target: list available targets with their descriptions.
.DEFAULT_GOAL := help

help: ## List available targets
	@echo "Usage: make <target>"
	@echo
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## ' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

build: ## Build the entire workspace
	cargo build --workspace

test: ## Run all workspace tests
	cargo test --workspace --all-targets

run: ## Run the ferrogate CLI (pass args with ARGS="...")
	cargo run -p ferrogate-cli --bin ferrogate -- $(ARGS)

run-cmis: ## Run the cmis service
	cargo run -p cmis

run-mia: ## Run the mia service
	cargo run -p mia

fmt: ## Format all code
	cargo fmt --all

fmt-check: ## Check formatting without modifying files
	cargo fmt --all -- --check

lint: ## Run clippy with warnings denied
	cargo clippy --workspace --all-targets -- -D warnings

check: ## Type-check the workspace
	cargo check --workspace --all-targets

audit: ## Audit dependencies for known vulnerabilities
	cargo audit

deny: ## Run cargo-deny checks
	cargo deny check

coverage: ## Generate LCOV coverage report
	cargo llvm-cov --workspace --lcov --output-path lcov.info

clean: ## Remove build artifacts
	cargo clean

docs: ## Serve the Docsify documentation site locally (PORT=3000 by default)
	./serve-docs.sh $(PORT)

# Container image. Builds a linux/amd64 runtime image that runs the `cmis`
# server as an unprivileged user and bundles the `ferrogate` operator CLI (for
# `docker exec`). Exposes /opt/ferrogate/logs as a mountable volume and exports
# the FerroGate configuration env vars. Override the tag with
# IMAGE="repo/name:tag".
# Tag the image with the workspace crate version from Cargo.toml's
# [workspace.package] section (e.g. 0.12.0).
CARGO_VERSION := $(shell awk '/^\[workspace.package\]/{p=1} p&&/^version/{gsub(/[" ]/,"",$$3); print $$3; exit}' Cargo.toml)
IMAGE ?= ferrogate:$(CARGO_VERSION)

# Host OS/arch, used by the install and packaging targets to pick OS-appropriate
# locations and binary names.
UNAME_S := $(shell uname -s)
HOST_ARCH := $(shell uname -m)

# Client assets (service definitions, env/config templates) and the daemon label.
MIA_DIST  := crates/mia/dist
MIA_LABEL := com.ferrogate.mia

docker-image: ## Build the linux/amd64 ferrogate runtime image (IMAGE=tag to override)
	docker buildx build --platform linux/amd64 \
		-f docker/ferrogate.Dockerfile \
		-t $(IMAGE) \
		--load .
	@echo "Built $(IMAGE)"
	@echo "Run:  docker run --rm -v \"\$$PWD/logs:/opt/ferrogate/logs\" -e RUST_LOG=debug $(IMAGE) cmis"
	@echo "CLI:  docker exec <container> ferrogate status"

# ── Container image push ──────────────────────────────────────────────
#
# `make docker-image-push` is a one-command flow: on first use it asks which
# registry to push to and which credentials to use, saves the choice OUTSIDE
# the git repo (in $(PUSH_CONFIG)), then builds and pushes. Later runs reuse
# the saved config silently. Re-run the questions any time with
# `make docker-repo-setup`; inspect with `make docker-repo-show`.
#
# The password is never written to our config — `docker login` stores it in
# docker's own credential store. Only the registry/namespace/image and
# username are saved; the version tag always tracks Cargo.toml (override
# per-push with PUSH_TAG=...).
#
# Config lives under XDG config (or ~/.config) so it survives `git clean`.
PUSH_CONFIG ?= $(or $(XDG_CONFIG_HOME),$(HOME)/.config)/ferrogate/push.env

docker-repo-setup: ## Interactively choose the push registry + credentials; saves to $(PUSH_CONFIG)
	@mkdir -p $(dir $(PUSH_CONFIG))
	@echo "==> FerroGate container image — push registry setup"
	@echo "    Saved to: $(PUSH_CONFIG)  (outside the git repo)"
	@echo "    Press Enter to accept the [default] shown for each prompt."
	@echo ""
	@printf "  Registry host[:port]  (required)              : "; read REG; \
	 printf "  Scheme (http|https)   [https]                 : "; read SCH; \
	 printf "  Namespace / project   [none]                  : "; read NS;  \
	 printf "  Image name            [ferrogate]             : "; read IMG; \
	 printf "  Registry username     [skip login]            : "; read USR; \
	 if [ -z "$$REG" ]; then echo "ERROR: registry host is required"; exit 1; fi; \
	 SCH=$${SCH:-https}; IMG=$${IMG:-ferrogate}; \
	 case "$$SCH" in http|https) ;; *) echo "ERROR: scheme must be http or https"; exit 1 ;; esac; \
	 umask 077; \
	 { echo "# FerroGate push config — generated by 'make docker-repo-setup'."; \
	   echo "# The registry password is NOT stored here; docker login keeps it."; \
	   echo "REGISTRY=$$REG"; echo "SCHEME=$$SCH"; echo "NAMESPACE=$$NS"; \
	   echo "IMAGE_NAME=$$IMG"; echo "USERNAME=$$USR"; \
	 } > $(PUSH_CONFIG); chmod 600 $(PUSH_CONFIG); \
	 echo ""; echo "==> Wrote $(PUSH_CONFIG):"; sed 's/^/    /' $(PUSH_CONFIG); echo ""; \
	 if [ -n "$$USR" ]; then \
	   echo "==> logging in to $$REG as $$USR"; \
	   docker login -u "$$USR" "$$REG" || echo "WARNING: docker login failed — retry at push time."; \
	 fi

docker-repo-show: ## Print the saved push registry config ($(PUSH_CONFIG))
	@if [ ! -f $(PUSH_CONFIG) ]; then echo "Not configured yet — run 'make docker-repo-setup'."; exit 1; fi
	@echo "==> $(PUSH_CONFIG)"; sed 's/^/    /' $(PUSH_CONFIG)

docker-image-push: ## Push the image to the saved registry (asks on first use, then reuses)
	@if [ ! -f $(PUSH_CONFIG) ]; then \
		echo "No push registry configured yet — let's set one up."; echo ""; \
		$(MAKE) --no-print-directory docker-repo-setup; \
	fi
	@. $(PUSH_CONFIG); \
	 SCHEME=$${SCHEME:-https}; VTAG=$${PUSH_TAG:-$(CARGO_VERSION)}; \
	 if [ -n "$$NAMESPACE" ]; then REMOTE="$$REGISTRY/$$NAMESPACE/$$IMAGE_NAME"; \
	 else REMOTE="$$REGISTRY/$$IMAGE_NAME"; fi; \
	 if [ "$$SCHEME" = "http" ] && ! grep -q "$$REGISTRY" $$HOME/.docker/config.json 2>/dev/null; then \
	   echo "NOTE: $$REGISTRY is HTTP — it must be in /etc/docker/daemon.json \"insecure-registries\"."; \
	 fi; \
	 if ! grep -q "\"$$REGISTRY\"" "$$HOME/.docker/config.json" 2>/dev/null; then \
	   echo "==> not logged in to $$REGISTRY"; \
	   if [ -n "$$USERNAME" ]; then docker login -u "$$USERNAME" "$$REGISTRY"; else docker login "$$REGISTRY"; fi \
	     || { echo "ERROR: login to $$REGISTRY failed"; exit 1; }; \
	 fi; \
	 echo "==> building image $(IMAGE)"; \
	 $(MAKE) --no-print-directory docker-image; \
	 echo "==> tagging $(IMAGE) as $$REMOTE:$$VTAG and :latest"; \
	 docker tag $(IMAGE) "$$REMOTE:$$VTAG"; \
	 docker tag $(IMAGE) "$$REMOTE:latest"; \
	 echo "==> pushing $$REMOTE:$$VTAG"; docker push "$$REMOTE:$$VTAG"; \
	 echo "==> pushing $$REMOTE:latest"; docker push "$$REMOTE:latest"; \
	 echo ""; echo "==> Push complete: $$REMOTE:$$VTAG and $$REMOTE:latest"

# Formal verification (feature: M6). Both targets degrade gracefully when the
# prover is not installed locally; CI installs both so the gate is real there.
# Per-proof wall-clock ceiling in seconds (CI sets this explicitly).
FERROGATE_FORMAL_TIMEOUT ?= 600

formal: formal-tamarin formal-cryptoverif ## Run all formal verification proofs

formal-tamarin: ## Run the Tamarin attestation proof
	@if command -v tamarin-prover >/dev/null 2>&1; then \
		echo "==> Tamarin: formal/tamarin/attestation.spthy"; \
		tamarin-prover --prove formal/tamarin/attestation.spthy; \
	else \
		echo "SKIP: tamarin-prover not on PATH (see formal/README.md to install)"; \
	fi

formal-cryptoverif: ## Run the CryptoVerif hybrid AKE proof
	@if command -v cryptoverif >/dev/null 2>&1; then \
		echo "==> CryptoVerif: formal/cryptoverif/hybrid_ake.cv"; \
		cryptoverif formal/cryptoverif/hybrid_ake.cv; \
	else \
		echo "SKIP: cryptoverif not on PATH (see formal/README.md to install)"; \
	fi

# ── Local install ─────────────────────────────────────────────────────────────
#
# `make mia-install` compiles the `mia` Machine Identity Agent in release mode,
# installs the stripped binary to an OS-appropriate location, AND registers the
# OS service so it runs as a daemon:
#
#   macOS : /usr/local/bin/mia  + launchd job at
#           /Library/LaunchDaemons/com.ferrogate.mia.plist (bootstrapped+started)
#   Linux : /usr/local/bin/mia  + systemd unit /etc/systemd/system/mia.service
#           (daemon-reload + enable --now)
#   Windows : $(PREFIX)\mia.exe (binary only; the service is registered by the
#           .msi — run `make pkg-msi`). PREFIX defaults to
#           %LOCALAPPDATA%\Programs\FerroGate; run under MSYS2/Git-Bash.
#
# Override the binary location with PREFIX=... (e.g. PREFIX=$$HOME/.local for a
# user-only Unix install). The privileged steps (binary into a non-writable dir,
# service registration) run via sudo when not already root.
ifneq (,$(filter MINGW% MSYS% CYGWIN% Windows%,$(UNAME_S)))
  MIA_OS  := windows
  PREFIX  ?= $(LOCALAPPDATA)/Programs/FerroGate
  BINDIR  := $(PREFIX)
  MIA_BIN := mia.exe
else ifeq ($(UNAME_S),Darwin)
  MIA_OS    := macos
  PREFIX    ?= /usr/local
  BINDIR    := $(PREFIX)/bin
  MIA_BIN   := mia
  # macOS service-account groups conventionally carry a leading underscore.
  MIA_GROUP := _ferrogate
else
  MIA_OS    := linux
  PREFIX    ?= /usr/local
  BINDIR    := $(PREFIX)/bin
  MIA_BIN   := mia
  MIA_GROUP := ferrogate
endif

mia-install: ## Compile mia in release mode, install it, and register the OS service (PREFIX=... to override)
	@# Build as the invoking user even under `sudo make`, so target/ never becomes root-owned.
	@if [ "$$(id -u)" -eq 0 ] && [ -n "$$SUDO_USER" ]; then \
	  echo "==> building as $$SUDO_USER (keeping target/ user-owned)"; \
	  sudo -u "$$SUDO_USER" cargo build --release -p mia --bin mia; \
	  sudo -u "$$SUDO_USER" strip target/release/$(MIA_BIN); \
	else \
	  cargo build --release -p mia --bin mia; \
	  strip target/release/$(MIA_BIN); \
	fi
ifeq ($(MIA_OS),windows)
	@mkdir -p "$(BINDIR)"
	@cp -f target/release/$(MIA_BIN) "$(BINDIR)/$(MIA_BIN)"
	@echo "==> installed mia to $(BINDIR)/$(MIA_BIN)"
	@echo "    Add $(BINDIR) to your PATH if it isn't already."
	@echo "    Windows service registration is handled by the .msi — run 'make pkg-msi'."
else
	@if [ -w "$(BINDIR)" ] || { [ ! -e "$(BINDIR)" ] && [ -w "$(PREFIX)" ]; }; then \
	  install -d -m 0755 "$(BINDIR)"; \
	  install -m 0755 target/release/$(MIA_BIN) "$(BINDIR)/$(MIA_BIN)"; \
	else \
	  echo "==> $(BINDIR) not writable; installing with sudo"; \
	  sudo install -d -m 0755 "$(BINDIR)"; \
	  sudo install -m 0755 target/release/$(MIA_BIN) "$(BINDIR)/$(MIA_BIN)"; \
	fi
	@echo "==> installed mia to $(BINDIR)/$(MIA_BIN)"
endif
ifeq ($(MIA_OS),macos)
	@echo "==> registering launchd daemon $(MIA_LABEL)"
	@SUDO=$$( [ "$$(id -u)" -eq 0 ] && echo "" || echo sudo ); \
	  DEST=/Library/LaunchDaemons/$(MIA_LABEL).plist; \
	  GID=$$( $$SUDO ./scripts/ferrogate-group.sh $(MIA_GROUP) ); \
	  $$SUDO sh -c "sed 's|<string>/usr/local/bin/mia</string>|<string>$(BINDIR)/$(MIA_BIN)</string>|' $(MIA_DIST)/$(MIA_LABEL).plist > $$DEST"; \
	  $$SUDO chmod 0644 $$DEST; \
	  $$SUDO /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables:FERROGATE_HELPER_SOCKET_GID string $$GID" $$DEST 2>/dev/null \
	    || $$SUDO /usr/libexec/PlistBuddy -c "Set :EnvironmentVariables:FERROGATE_HELPER_SOCKET_GID $$GID" $$DEST; \
	  $$SUDO mkdir -p /var/log/ferrogate; \
	  $$SUDO launchctl bootout system $$DEST 2>/dev/null || true; \
	  $$SUDO launchctl bootstrap system $$DEST; \
	  $$SUDO launchctl kickstart -k system/$(MIA_LABEL); \
	  echo "==> helper socket will be owned by group $(MIA_GROUP) (gid $$GID), mode 0660"
	@echo "==> launchd job $(MIA_LABEL) loaded and started"
	@echo "    Configure it with: sudo mia setup   (writes the system TOML the daemon reads)"
	@command -v mia >/dev/null 2>&1 || echo "NOTE: $(BINDIR) is not on your PATH."
endif
ifeq ($(MIA_OS),linux)
	@echo "==> installing systemd unit mia.service"
	@SUDO=$$( [ "$$(id -u)" -eq 0 ] && echo "" || echo sudo ); \
	  GID=$$( $$SUDO ./scripts/ferrogate-group.sh $(MIA_GROUP) ); \
	  $$SUDO sh -c "sed 's|^ExecStart=.*|ExecStart=$(BINDIR)/$(MIA_BIN)|' $(MIA_DIST)/mia.service > /etc/systemd/system/mia.service"; \
	  $$SUDO chmod 0644 /etc/systemd/system/mia.service; \
	  $$SUDO mkdir -p /etc/systemd/system/mia.service.d; \
	  printf '[Service]\nEnvironment=FERROGATE_HELPER_SOCKET_GID=%s\n# 0755 so group members can traverse /run/ferrogate to the 0660 socket.\nRuntimeDirectoryMode=0755\n' "$$GID" \
	    | $$SUDO tee /etc/systemd/system/mia.service.d/10-helper-group.conf >/dev/null; \
	  $$SUDO systemctl daemon-reload; \
	  $$SUDO systemctl enable --now mia.service \
	    || echo "   (enable failed — configure /etc/ferrogate then: sudo systemctl enable --now mia)"; \
	  echo "==> helper socket will be owned by group $(MIA_GROUP) (gid $$GID), mode 0660"
	@echo "==> systemd unit mia.service installed"
	@echo "    Configure it with: sudo mia setup   (writes the system TOML the daemon reads)"
	@command -v mia >/dev/null 2>&1 || echo "NOTE: $(BINDIR) is not on your PATH."
endif

# `make mia-uninstall` reverses `mia-install`: it deregisters the OS service and
# removes the installed binary. It leaves configuration, the env file, logs, and
# the socket alone (use `mia setup --clean` to remove the config). Each step
# tolerates an already-absent target, so it is safe to run repeatedly.
mia-uninstall: ## Stop/deregister the mia service and remove the installed binary (PREFIX=... to override)
ifeq ($(MIA_OS),windows)
	@rm -f "$(BINDIR)/$(MIA_BIN)" && echo "==> removed $(BINDIR)/$(MIA_BIN)" || true
	@echo "    Windows service deregistration is handled by the .msi uninstaller."
else ifeq ($(MIA_OS),macos)
	@echo "==> deregistering launchd daemon $(MIA_LABEL)"
	@SUDO=$$( [ "$$(id -u)" -eq 0 ] && echo "" || echo sudo ); \
	  $$SUDO launchctl bootout system /Library/LaunchDaemons/$(MIA_LABEL).plist 2>/dev/null || true; \
	  $$SUDO rm -f /Library/LaunchDaemons/$(MIA_LABEL).plist; \
	  $$SUDO rm -f "$(BINDIR)/$(MIA_BIN)"
	@echo "==> removed launchd job and $(BINDIR)/$(MIA_BIN)"
	@echo "    Config, logs, and the socket are left in place (run 'sudo mia setup --clean' to drop the config)."
else
	@echo "==> deregistering systemd unit mia.service"
	@SUDO=$$( [ "$$(id -u)" -eq 0 ] && echo "" || echo sudo ); \
	  $$SUDO systemctl disable --now mia.service 2>/dev/null || true; \
	  $$SUDO rm -f /etc/systemd/system/mia.service; \
	  $$SUDO rm -rf /etc/systemd/system/mia.service.d; \
	  $$SUDO systemctl daemon-reload 2>/dev/null || true; \
	  $$SUDO rm -f "$(BINDIR)/$(MIA_BIN)"
	@echo "==> removed systemd unit and $(BINDIR)/$(MIA_BIN)"
	@echo "    Config, logs, and the socket are left in place (run 'sudo mia setup --clean' to drop the config)."
endif

# ── Client packaging: rpm / deb / msi / pkg ───────────────────────────────────
#
# Builds OS installer packages for the FerroGate *client* — the `mia` Machine
# Identity Agent. Each format uses the dedicated packaging tool and reads its
# metadata from `crates/mia/Cargo.toml` (deb/rpm/msi) plus the assets in
# `crates/mia/dist/`:
#
#   make pkg-deb   -> .deb   (cargo-deb,          Debian/Ubuntu)
#   make pkg-rpm   -> .rpm   (cargo-generate-rpm, Fedora/RHEL/SUSE)
#   make pkg-msi   -> .msi   (cargo-wix,          Windows; run ON Windows)
#   make pkg-macos -> .pkg   (pkgbuild/productbuild, macOS; run ON macOS)
#   make pkg       -> every format valid for the current host
#   make pkg-tools -> install the cargo packaging tools (deb/rpm/msi)
#
# Each package must be built on its target OS: DEB/RPM on Linux (the release
# binary links the Linux TPM ESAPI stack), MSI on Windows with the WiX Toolset
# v3, the .pkg on macOS (no TPM there — mia runs as the helper-API surface).
# Outputs land under target/debian, target/generate-rpm, target/wix, target/macos.
PKG_CRATE := mia
# RPM/DEB ship for amd64 only; mia links the x86_64 Linux TPM ESAPI stack.
RPM_ARCH  := x86_64

pkg-tools: ## Install the cargo packaging tools (cargo-deb, cargo-generate-rpm, cargo-wix)
	cargo install cargo-deb cargo-generate-rpm cargo-wix

pkg-deb: ## Build the mia .deb package (Linux; needs cargo-deb)
	@command -v cargo-deb >/dev/null 2>&1 || { echo "ERROR: cargo-deb not found — run 'make pkg-tools'"; exit 1; }
	cargo deb -p $(PKG_CRATE)
	@echo "==> .deb written under target/debian/"

pkg-rpm: ## Build the mia .rpm package for x86_64/amd64 (Fedora/RHEL/SUSE)
ifeq ($(UNAME_S)/$(HOST_ARCH),Linux/x86_64)
	@command -v cargo-generate-rpm >/dev/null 2>&1 || { echo "ERROR: cargo-generate-rpm not found — run 'make pkg-tools'"; exit 1; }
	cargo build --release -p $(PKG_CRATE) --bin $(PKG_CRATE)
	strip target/release/$(PKG_CRATE)
	cargo generate-rpm -p crates/$(PKG_CRATE) -a $(RPM_ARCH)
	@echo "==> $(RPM_ARCH) .rpm written under target/generate-rpm/"
else
	@echo "==> host is $(UNAME_S)/$(HOST_ARCH), not Linux/x86_64; building the amd64 .rpm in a linux/amd64 container"
	./scripts/build-rpm-amd64.sh
endif

pkg-msi: ## Build the mia .msi installer (Windows; needs cargo-wix + WiX Toolset)
	@command -v cargo-wix >/dev/null 2>&1 || { echo "ERROR: cargo-wix not found — run 'make pkg-tools'"; exit 1; }
	cargo wix -p $(PKG_CRATE) --nocapture
	@echo "==> .msi written under target/wix/"

# macOS component+product package built with the platform's own tools (no extra
# cargo plugin). Stages a payload root, then pkgbuild → productbuild. Set
# PKG_SIGN_ID="Developer ID Installer: ..." to sign the product archive.
MACOS_PKG_ID   := com.ferrogate.mia
MACOS_PKG_ROOT := target/macos/pkgroot
MACOS_PKG_OUT  := target/macos/ferrogate-mia-$(CARGO_VERSION).pkg
MACOS_DIST     := crates/mia/dist
pkg-macos: ## Build the mia .pkg installer (macOS; uses pkgbuild/productbuild)
	@[ "$(UNAME_S)" = "Darwin" ] || { echo "ERROR: pkg-macos must run on macOS (host is $(UNAME_S))"; exit 1; }
	cargo build --release -p $(PKG_CRATE) --bin $(PKG_CRATE)
	strip target/release/$(PKG_CRATE)
	rm -rf $(MACOS_PKG_ROOT)
	install -d -m 0755 $(MACOS_PKG_ROOT)/usr/local/bin
	install -d -m 0755 $(MACOS_PKG_ROOT)/etc/ferrogate
	install -d -m 0755 "$(MACOS_PKG_ROOT)/Library/Application Support/FerroGate"
	install -d -m 0755 $(MACOS_PKG_ROOT)/Library/LaunchDaemons
	install -m 0755 target/release/$(PKG_CRATE) $(MACOS_PKG_ROOT)/usr/local/bin/$(PKG_CRATE)
	install -m 0640 $(MACOS_DIST)/mia.env $(MACOS_PKG_ROOT)/etc/ferrogate/mia.env
	# The TOML config goes to the macOS system config path (where mia discovers it).
	install -m 0640 $(MACOS_DIST)/mia.toml "$(MACOS_PKG_ROOT)/Library/Application Support/FerroGate/mia.toml"
	install -m 0644 $(MACOS_DIST)/com.ferrogate.mia.plist $(MACOS_PKG_ROOT)/Library/LaunchDaemons/$(MACOS_PKG_ID).plist
	pkgbuild --root $(MACOS_PKG_ROOT) \
		--scripts $(MACOS_DIST)/macos-scripts \
		--identifier $(MACOS_PKG_ID) \
		--version $(CARGO_VERSION) \
		--install-location / \
		target/macos/$(PKG_CRATE)-component.pkg
	productbuild --package target/macos/$(PKG_CRATE)-component.pkg \
		$(if $(PKG_SIGN_ID),--sign "$(PKG_SIGN_ID)",) \
		$(MACOS_PKG_OUT)
	@rm -f target/macos/$(PKG_CRATE)-component.pkg
	@echo "==> .pkg written to $(MACOS_PKG_OUT)"

pkg: ## Build every client package valid for this host (deb+rpm/Linux, msi/Windows, pkg/macOS)
	@case "$(UNAME_S)" in \
	  Linux)  $(MAKE) --no-print-directory pkg-deb pkg-rpm; \
	          echo "NOTE: build the .msi on Windows ('make pkg-msi') and the .pkg on macOS ('make pkg-macos')." ;; \
	  Darwin) $(MAKE) --no-print-directory pkg-macos; \
	          echo "NOTE: build the .deb/.rpm on Linux ('make pkg') and the .msi on Windows ('make pkg-msi')." ;; \
	  *)      echo "Host is $(UNAME_S): build the .msi here with 'make pkg-msi'."; \
	          $(MAKE) --no-print-directory pkg-msi ;; \
	esac

# ── Integration SDK + release bundle ──────────────────────────────────────────
#
# `make pkg-sdk` bundles the relying-party / verifier-side crates into a
# self-contained Cargo workspace tarball (ferrogate-sdk-rust-<version>.tgz) that
# a third party can drop in and `cargo build`. See scripts/pack-sdk.sh.
#
# `make release` produces the artifacts published to a GitHub Release: the mia
# .deb, the mia .rpm, and the SDK .tgz. It is the entry point the release
# workflow (.github/workflows/release.yml) runs on a `releases/*` tag. On Linux
# it builds all three; off Linux it builds only the SDK (deb/rpm need a Linux
# host) and says so.
#
# `make deploy-release` cuts the release: it creates the annotated
# `releases/v<workspace-version>` tag and pushes it to origin, which is what
# triggers the Release workflow (the workflow then checks the tag out and runs
# `make release` to build + publish the artifacts). Bump the workspace version
# and commit first; this target only tags and pushes.
pkg-sdk: ## Build the ferrogate-sdk-rust integration tarball (.tgz)
	bash scripts/pack-sdk.sh

release: ## Build the GitHub Release artifacts (mia .deb + .rpm + SDK .tgz)
	@case "$(UNAME_S)" in \
	  Linux) $(MAKE) --no-print-directory pkg-deb pkg-rpm pkg-sdk; \
	         echo ""; echo "==> Release artifacts:"; \
	         ls -1 target/debian/*.deb target/generate-rpm/*.rpm target/sdk/*.tgz 2>/dev/null ;; \
	  *)     echo "Host is $(UNAME_S): the .deb/.rpm must be built on Linux."; \
	         echo "Building the SDK tarball only."; \
	         $(MAKE) --no-print-directory pkg-sdk ;; \
	esac

deploy-release: ## Tag releases/v<workspace-version> and push it to trigger the Release workflow
	@VERSION="$(CARGO_VERSION)"; TAG="releases/v$$VERSION"; \
	if [ -z "$$VERSION" ]; then \
	  echo "error: could not read the workspace version from Cargo.toml." >&2; exit 1; \
	fi; \
	if [ -n "$$(git status --porcelain)" ]; then \
	  echo "error: working tree is dirty; commit the version bump before tagging." >&2; exit 1; \
	fi; \
	if git rev-parse -q --verify "refs/tags/$$TAG" >/dev/null 2>&1; then \
	  echo "error: tag $$TAG already exists (bump the workspace version first)." >&2; exit 1; \
	fi; \
	echo "==> Tagging $$TAG at $$(git rev-parse --short HEAD) and pushing to origin"; \
	echo "    (this triggers .github/workflows/release.yml, which runs 'make release')"; \
	git tag -a "$$TAG" -m "Release v$$VERSION"; \
	git push origin "$$TAG"
